name: Official status request
description: File a offical status request
title: "[OFICIAL]: Your repository or project name"
labels: ["official status request"]
assignees:
  - cynthia-sg
body:
  - type: markdown
    attributes:
      value: |
        In Artifact Hub, the `official` status means that the publisher **owns the software** a package primarily focuses on. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (*HashiCorp* in this case), not just the chart. Similarly, a [Tekton task used to perform operations on Google Cloud](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/gcloud) would need to be published by *Google* to be marked as `official`. In the case of a MySQL operator, only one published by *MySQL/Oracle* would be considered `official`.

        The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.
  - type: input
    id: repo_name
    attributes:
      label: Repository name
      description: Repository name in `artifacthub.io`
      placeholder: ex. prometheus
    validations:
      required: true
  - type: textarea
    id: packages
    attributes:
      label: Official packages
      description: leave empty if all packages in the repository are official
      placeholder: package1
      value: "..."
    validations:
      required: false
  - type: input
    id: code
    attributes:
      label: Source code
      description: if available
    validations:
      required: false
  - type: textarea
    id: urls
    attributes:
      label: Other relevant URLs
      description: if there are any other urls that can help us with the verification process, please include them here
  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      description: Before applying for this status, please make sure your repository complies with the following requirements
      options:
        - label: The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
          required: true
        - label: The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
          required: true
        - label: All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.
          required: true
